version: '3.8'

services:
  kali-server:
    build: .
    container_name: mcp-kali-server
    image: mcp-kali-server:latest
    ports:
      - "5000:5000"
    environment:
      - API_PORT=5000
      - DEBUG_MODE=0
      - COMMAND_TIMEOUT=180
    volumes:
      # Mount for persistent data if needed
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python3", "-c", "import requests; requests.get('http://localhost:5000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - mcp-network
    # Security options
    security_opt:
      - no-new-privileges:true
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 256M

networks:
  mcp-network:
    driver: bridge
