name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "Error: requirements.txt not found!"
            exit 1
          fi
          pip install pylint flake8 pytest

      # Step 4: Lint Python code with Pylint
      - name: Lint with Pylint
        run: pylint **/*.py

      # Step 5: Lint Python code with Flake8
      - name: Lint with Flake8
        run: flake8 .

      # Step 6: Run Tests
      - name: Run Tests
        run: pytest -v --maxfail=1 --disable-warnings

      # Step 7: Build Docker image
      - name: Build Docker image
        run: docker build -t mcp-kali-server:latest .